/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2019-2024 Hailo Technologies Ltd. All rights reserved.
 */

#ifndef HAILO15_SCMI_API_H
#define HAILO15_SCMI_API_H

#define HAILO_SOC_HAILO15 1
#define HAILO_SOC_HAILO15L 2
#define HAILO_SOC_HAILO10H2 3

#ifndef HAILO_SOC_TYPE
#    error "HAILO_SOC_TYPE is not defined"
#endif

#define HAILO15_SCMI_SENSOR_IDX_PVT_TEMPERATURE_SENSOR_0 0
#define HAILO15_SCMI_SENSOR_IDX_PVT_TEMPERATURE_SENSOR_1 1

/* Clocks IDs */
#if (HAILO_SOC_TYPE == HAILO_SOC_HAILO15) || (HAILO_SOC_TYPE == HAILO_SOC_HAILO15L)
#    define HAILO15_SCMI_CLOCK_IDX_HCLK 0
#    define HAILO15_SCMI_CLOCK_IDX_SDIO_0_M_HCLK 1
#    define HAILO15_SCMI_CLOCK_IDX_SDIO_1_M_HCLK 2
#    define HAILO15_SCMI_CLOCK_IDX_DSP_CONFIG 3
#    define HAILO15_SCMI_CLOCK_IDX_DSP_PLL 4
#    define HAILO15_SCMI_CLOCK_IDX_DSP 5
#    define HAILO15_SCMI_CLOCK_IDX_ETHERNET_PCLK 6
#    define HAILO15_SCMI_CLOCK_IDX_ETHERNET_ACLK 7
#    define HAILO15_SCMI_CLOCK_IDX_SDIO_0_CARD_CLK 8
#    define HAILO15_SCMI_CLOCK_IDX_SDIO_1_CARD_CLK 9
#    define HAILO15_SCMI_CLOCK_IDX_VISION_HCLK 10
#    define HAILO15_SCMI_CLOCK_IDX_ISP_WRAPPER_PCLK 11
#    define HAILO15_SCMI_CLOCK_IDX_CSI_RX0_PCLK 12
#    define HAILO15_SCMI_CLOCK_IDX_CSI_RX1_PCLK 13
#    define HAILO15_SCMI_CLOCK_IDX_CSI_TX0_PCLK 14
#    define HAILO15_SCMI_CLOCK_IDX_VISION_CLK 15
#    define HAILO15_SCMI_CLOCK_IDX_ISP_WRAPPER_CLK 16
#    define HAILO15_SCMI_CLOCK_IDX_CSI_RX0_CLK 17
#    define HAILO15_SCMI_CLOCK_IDX_CSI_RX1_CLK 18
#    define HAILO15_SCMI_CLOCK_IDX_CSI_TX0_CLK 19
#    define HAILO15_SCMI_CLOCK_IDX_CSI_RX0_XTAL_CLK 20
#    define HAILO15_SCMI_CLOCK_IDX_CSI_RX1_XTAL_CLK 21
#    define HAILO15_SCMI_CLOCK_IDX_CSI_TX0_XTAL_CLK 22
#    define HAILO15_SCMI_CLOCK_IDX_MIPI_REF_CLK 23
#    define HAILO15_SCMI_CLOCK_IDX_MIPI_ESC_CLK 24
#    define HAILO15_SCMI_CLOCK_IDX_SDIO_0_CLK_DIV_BYPASS 25
#    define HAILO15_SCMI_CLOCK_IDX_SDIO_1_CLK_DIV_BYPASS 26
#    define HAILO15_SCMI_CLOCK_IDX_PCIE_REFCLK 27
#    define HAILO15_SCMI_CLOCK_IDX_H265_HCLK 28
#    define HAILO15_SCMI_CLOCK_IDX_H265_CLK 29
#    define HAILO15_SCMI_CLOCK_IDX_USB_PCLK 30
#    define HAILO15_SCMI_CLOCK_IDX_USB_LPM_CLK 31
#    define HAILO15_SCMI_CLOCK_IDX_USB2_REFCLK 32
#    define HAILO15_SCMI_CLOCK_IDX_USB_ACLK 33
#    define HAILO15_SCMI_CLOCK_IDX_USB_SOF_CLK 34
#    define HAILO15_SCMI_CLOCK_IDX_PCIE_PCLK 35
#    define HAILO15_SCMI_CLOCK_IDX_PCIE_ACLK 36
#    define HAILO15_SCMI_CLOCK_IDX_VIRTUAL_DSP 37
#    if HAILO_SOC_TYPE == HAILO_SOC_HAILO15
#        define HAILO15_SCMI_CLOCK_IDX_I2S_CLK_DIV 38
#    elif HAILO_SOC_TYPE == HAILO_SOC_HAILO15L
#        define HAILO15_SCMI_CLOCK_IDX_ISP_HDR_STITCH 38
#        define HAILO15_SCMI_CLOCK_IDX_I2C_0 39
#        define HAILO15_SCMI_CLOCK_IDX_I2C_1 40
#        define HAILO15_SCMI_CLOCK_IDX_I2C_2 41
#        define HAILO15_SCMI_CLOCK_IDX_I2C_3 42
#        define HAILO15_SCMI_CLOCK_IDX_SPI_0_GATE 43
#        define HAILO15_SCMI_CLOCK_IDX_SPI_1_GATE 44
#        define HAILO15_SCMI_CLOCK_IDX_SPI_2_GATE 45
#        define HAILO15_SCMI_CLOCK_IDX_SPI_3_GATE 46
#    endif /* HAILO_SOC_HAILO15L */
#elif HAILO_SOC_TYPE == HAILO_SOC_HAILO10H2
#    define HAILO15_SCMI_CLOCK_IDX_HCLK 0
#    define HAILO15_SCMI_CLOCK_IDX_SDIO_1_M_HCLK 1
#    define HAILO15_SCMI_CLOCK_IDX_DSP_CONFIG 2
#    define HAILO15_SCMI_CLOCK_IDX_DSP_PLL 3
#    define HAILO15_SCMI_CLOCK_IDX_DSP 4
#    define HAILO15_SCMI_CLOCK_IDX_SDIO_1_CARD_CLK 5
#    define HAILO15_SCMI_CLOCK_IDX_SDIO_0_CLK_DIV_BYPASS 6
#    define HAILO15_SCMI_CLOCK_IDX_SDIO_1_CLK_DIV_BYPASS 7
#    define HAILO15_SCMI_CLOCK_IDX_PCIE_REFCLK 8
#    define HAILO15_SCMI_CLOCK_IDX_USB_PCLK 9
#    define HAILO15_SCMI_CLOCK_IDX_USB_LPM_CLK 10
#    define HAILO15_SCMI_CLOCK_IDX_USB2_REFCLK 11
#    define HAILO15_SCMI_CLOCK_IDX_USB_ACLK 12
#    define HAILO15_SCMI_CLOCK_IDX_USB_SOF_CLK 13
#    define HAILO15_SCMI_CLOCK_IDX_PCIE_PCLK 14
#    define HAILO15_SCMI_CLOCK_IDX_PCIE_ACLK 15
#    define HAILO15_SCMI_CLOCK_IDX_VIRTUAL_DSP 16
#    define HAILO15_SCMI_CLOCK_IDX_I2C_0 17
#    define HAILO15_SCMI_CLOCK_IDX_I2C_1 18
#    define HAILO15_SCMI_CLOCK_IDX_I2C_2 19
#    define HAILO15_SCMI_CLOCK_IDX_I2C_3 20
#    define HAILO15_SCMI_CLOCK_IDX_SPI_0_GATE 21
#    define HAILO15_SCMI_CLOCK_IDX_SPI_1_GATE 22
#    define HAILO15_SCMI_CLOCK_IDX_SPI_2_GATE 23
#    define HAILO15_SCMI_CLOCK_IDX_SPI_3_GATE 24
#else
#    error "Unsupported HAILO_SOC_TYPE"
#endif /* HAILO_SOC_TYPE */

/* Resets IDs */
#define HAILO15_SCMI_RESET_IDX_CORE_CPU 0
#define HAILO15_SCMI_RESET_IDX_NN_CORE 1
#define HAILO15_SCMI_RESET_IDX_DSP 2
#define HAILO15_SCMI_RESET_IDX_SDIO_0_CD_FROM_PINMUX 3
#define HAILO15_SCMI_RESET_IDX_SDIO_1_CD_FROM_PINMUX 4
#define HAILO15_SCMI_RESET_IDX_PCIE_PHY_LANE_0 5
#define HAILO15_SCMI_RESET_IDX_PCIE_PHY_LANE_1 6
#define HAILO15_SCMI_RESET_IDX_PCIE_PHY_LANE_2 7
#define HAILO15_SCMI_RESET_IDX_PCIE_PHY_LANE_3 8
#define HAILO15_SCMI_RESET_IDX_PCIE_PHY 9
#if (HAILO_SOC_TYPE == HAILO_SOC_HAILO15) || (HAILO_SOC_TYPE == HAILO_SOC_HAILO15L)
#    define HAILO15_SCMI_RESET_IDX_H265 10
#    define HAILO15_SCMI_RESET_IDX_SDIO1_8BIT_MUX 11
#elif HAILO_SOC_TYPE == HAILO_SOC_HAILO10H2
/* No additional resets */
#else
#    error "Unsupported HAILO_SOC_TYPE"
#endif /* HAILO_SOC_TYPE */

/* Power domain IDs */
#if HAILO_SOC_TYPE == HAILO_SOC_HAILO15
#    define HAILO15_SCMI_POWER_DOMAIN_IDX_CSI_RX0 0
#    define HAILO15_SCMI_POWER_DOMAIN_IDX_CSI_RX1 1
#    define HAILO15_SCMI_POWER_DOMAIN_IDX_ISP 2
#    define HAILO15_SCMI_POWER_DOMAIN_IDX_DSP 3
#    define HAILO15_SCMI_POWER_DOMAIN_IDX_CSI_TX0 4
#    define HAILO15_SCMI_POWER_DOMAIN_IDX_VISION_SUBSYS 5
#    define HAILO15_SCMI_POWER_DOMAIN_IDX_PCIE 6
#    define HAILO15_SCMI_POWER_DOMAIN_IDX_USB 7
#    define HAILO15_SCMI_POWER_DOMAIN_IDX_H265 8
#    define HAILO15_SCMI_POWER_DOMAIN_IDX_SYSTOP 9
#    define HAILO15_SCMI_POWER_DOMAIN_COUNT 10
#elif HAILO_SOC_TYPE == HAILO_SOC_HAILO15L
#    define HAILO15_SCMI_POWER_DOMAIN_IDX_CSI_RX0 0
#    define HAILO15_SCMI_POWER_DOMAIN_IDX_CSI_TX0 1
#    define HAILO15_SCMI_POWER_DOMAIN_IDX_VISION_SUBSYS 2
#    define HAILO15_SCMI_POWER_DOMAIN_IDX_PCIE 3
#    define HAILO15_SCMI_POWER_DOMAIN_IDX_USB 4
#    define HAILO15_SCMI_POWER_DOMAIN_IDX_SYSTOP 5
#    define HAILO15_SCMI_POWER_DOMAIN_COUNT 6
#elif HAILO_SOC_TYPE == HAILO_SOC_HAILO10H2
#    define HAILO15_SCMI_POWER_DOMAIN_IDX_PCIE 0
#    define HAILO15_SCMI_POWER_DOMAIN_IDX_USB 1
#    define HAILO15_SCMI_POWER_DOMAIN_IDX_SYSTOP 2
#    define HAILO15_SCMI_POWER_DOMAIN_COUNT 3
#else
#    error "Unsupported HAILO_SOC_TYPE"
#endif /* HAILO_SOC_TYPE */

/* DVFS domain IDs */
#define HAILO15_SCMI_DVFS_DOMAIN_IDX_AP 0
#define HAILO15_SCMI_DVFS_DOMAIN_IDX_NN_CORE 1
#define HAILO15_SCMI_DVFS_DOMAIN_IDX_DSP 2
#define HAILO15_SCMI_DVFS_DOMAIN_COUNT 3

#endif /* HAILO15_SCMI_API_H */
